### ISSUE TITLE
Duplicate of Spring

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#120]
If jpsonic - 2.2.6 is deployed on jetty instead of standalone, the service does not start.

## Problem description

Cause is a startup exception "IllegalStateException: Duplicate fragment name: spring_web" .
It suggests that different versions of Spring are loaded in duplicate.

The fix assumed to have affected is 355868b.

## System information
 - Jetty 9.4.8 on CentOS 6,7
 - jpsonic-2.2.6 based on airsonic adc2241

### Steps to reproduce
Deploy jpsonic-2.2.6 on jetty instead of standalone.

### Log

2019-01-16 11:10:04.979:INFO:oejs.Server:main: jetty-9.4.8.v20171121, build timestamp: 2017-11-21T16:27:37-05:00, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
2019-01-16 11:10:05.006:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///opt/web/mybase/webapps/] at interval 1
2019-01-16 11:10:06.054:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@55d56113{/jpsonic,file:///opt/jetty/temp/jetty-0.0.0.0-28080-jpsonic.war-_jpsonic-any-765554881200720548.dir/webapp/,UNAVAILABLE}{/jpsonic.war}
java.lang.IllegalStateException: Duplicate fragment name: spring_web for jar:file:///opt/jetty/temp/jetty-0.0.0.0-28080-jpsonic.war-_jpsonic-any-765554881200720548.dir/webapp/WEB-INF/lib/spring-web-4.3.19.RELEASE.jar!/META-INF/web-fragment.xml and jar:file:///opt/jetty/temp/jetty-0.0.0.0-28080-jpsonic.war-_jpsonic-any-765554881200720548.dir/webapp/WEB-INF/lib/spring-web-4.3.21.RELEASE.jar!/META-INF/web-fragment.xml
	at org.eclipse.jetty.webapp.MetaData.addFragment(MetaData.java:284)
	at org.eclipse.jetty.webapp.FragmentConfiguration.addWebFragments(FragmentConfiguration.java:88)
	at org.eclipse.jetty.webapp.FragmentConfiguration.preConfigure(FragmentConfiguration.java:39)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:506)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:544)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:502)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:150)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:447)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:564)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:239)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.server.Server.start(Server.java:418)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:115)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:385)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1584)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1508)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1507)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:221)
	at org.eclipse.jetty.start.Main.start(Main.java:504)
	at org.eclipse.jetty.start.Main.main(Main.java:78)
2019-01-16 11:10:06.080:INFO:oejs.AbstractConnector:main: Started ServerConnector@5891e32e{HTTP/1.1,[http/1.1]}{0.0.0.0:28080}
2019-01-16 11:10:06.081:INFO:oejs.Server:main: Started @2018ms

## Additional notes

#86
#54

**Comment by tesshucom** [comment]
Updated the spring-boot-maven-plugin and unified Spring's version to 1.5.18.RELEASE.
With this fix, I confirmed that the service starts normally on Jetty.
