### ISSUE TITLE
Update Github Actions

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#1508]
## Problem description

> CodeQL Action v1 will be deprecated on December 7th, 2022. Please upgrade to v2. For more information, see https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/

However, other scripts will also be updated. Also version control will be transferred to Dependabot.
___

The setup itself is not difficult, and there seems to be no incompatibilities between older versions and scripts.

 - [Configure version updates for GitHub actions](https://github.com/tesshucom/jpsonic/commit/a21715a02d8c0585294c52e1974334aacc124d1c)
 - [Set schedule to github-actions updates](https://github.com/tesshucom/jpsonic/commit/2b0018142275abaac928c0cfa4b4fb87943c67f2)
 - [Update Github Actions](https://github.com/tesshucom/jpsonic/commit/fc1d644079c64f03ae132b9a3bcc6df25d1690db)

**Comment by tesshucom** [comment]
By the way, the above code has the following causes

```
Error: Exception in thread "pool-1-thread-1" java.io.UncheckedIOException: java.io.IOException: Stream closed
	at com.tesshu.jpsonic.io.TranscodeInputStream$TranscodedErrorStreamTask.run(TranscodeInputStream.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:168)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
	at com.tesshu.jpsonic.io.TranscodeInputStream$TranscodedErrorStreamTask.run(TranscodeInputStream.java:122)
	... 3 more
```
If Process's (in/out)stream is closed before reading the Process's errorStream.(There is the unit test case where Stream is requested and the response is forcibly closed immediately.) It is not possible to useUncheckedIOException in a place where IO is "silent-close"...
