### ISSUE TITLE
Problems with the 101.0.0 Upgrade

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#170]
DB upgrade (1.x-> 2.x) included.
However, since confirmation of normal operation has not been taken, investigation is required for a while.

-----

The bug encoding, Nullpointer, IndexOutOfException derived from YahooJSCompressor  occurs.
It is highly likely that you are in conflict with the fix around Service that you are using at Jpsonic.
Investigate the cause after the 100.1.0 release.

**Comment by tesshucom** [comment]
Now that #165 is complete, merged jpsonic 100.1.0 into the later 101.0.0.

**Comment by tesshucom** [comment]
An operation check on the server has confirmed a JavaScript encoding bug.
If no action is taken by the scheduled release date,
release 100.1.0 instead of 101.0.0 (do not import upstream).

**Comment by tesshucom** [comment]
```
2019-03-20 23:45:05.386  WARN --- o.d.servlet.JavaScriptHandler            : Compression system (YahooJSCompressor) failed to compress script

java.lang.RuntimeException: null
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.printSourceNumber(JavaScriptCompressor.java:299) ~[yuicompressor-2.3.6.jar:na]
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:335) ~[yuicompressor-2.3.6.jar:na]
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:532) ~[yuicompressor-2.3.6.jar:na]
        at org.directwebremoting.impl.YahooJSCompressor.compressJavaScript(YahooJSCompressor.java:76) ~[dwr-3.0.2-RELEASE.jar:na]
        at org.directwebremoting.servlet.JavaScriptHandler.generateCachableContent(JavaScriptHandler.java:55) ~[dwr-3.0.2-RELEASE.jar:na]
        at org.directwebremoting.servlet.FileJavaScriptHandler.generateCachableContent(FileJavaScriptHandler.java:61) [dwr-3.0.2-RELEASE.jar:na]
        at org.directwebremoting.servlet.CachingHandler.handle(CachingHandler.java:74) [dwr-3.0.2-RELEASE.jar:na]
        at org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:211) [dwr-3.0.2-RELEASE.jar:na]
        at org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:185) [dwr-3.0.2-RELEASE.jar:na]
        at org.directwebremoting.servlet.DwrServlet.doPost(DwrServlet.java:144) [dwr-3.0.2-RELEASE.jar:na]
        at org.directwebremoting.servlet.DwrServlet.doGet(DwrServlet.java:131) [dwr-3.0.2-RELEASE.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [servlet-api-3.1.jar:3.1.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
```

**Comment by tesshucom** [comment]
```
ERROR --- o.s.b.w.support.ErrorPageFilter          : Cannot forward to error page for request [/userChart.view] as the response has already been committed. As a result, the response may have the wrong status code. If your application is running on WebSphere Application Server you may be able to resolve this problem by setting com.ibm.ws.webcontainer.invokeFlushAfterService to false

javax.imageio.IIOException: I/O error writing PNG file!
        at com.sun.imageio.plugins.png.PNGImageWriter.write(PNGImageWriter.java:1168) ~[na:1.8.0_172]
        at javax.imageio.ImageWriter.write(ImageWriter.java:615) ~[na:1.8.0_172]
        at javax.imageio.ImageIO.doWrite(ImageIO.java:1612) ~[na:1.8.0_172]
        at javax.imageio.ImageIO.write(ImageIO.java:1578) ~[na:1.8.0_172]
        at org.jfree.chart.encoders.SunPNGEncoderAdapter.encode(SunPNGEncoderAdapter.java:127) ~[jfreechart-1.0.11.jar:na]
        at org.jfree.chart.encoders.EncoderUtil.writeBufferedImage(EncoderUtil.java:134) ~[jfreechart-1.0.11.jar:na]
        at org.jfree.chart.ChartUtils.writeChartAsPNG(ChartUtils.java:185) ~[jfreechart-1.5.0.jar:na]
        at org.jfree.chart.ChartUtils.writeChartAsPNG(ChartUtils.java:138) ~[jfreechart-1.5.0.jar:na]
        at org.airsonic.player.controller.UserChartController.handleRequest(UserChartController.java:72) ~[classes/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.21.RELEASE.jar:4.3.21.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.21.RELEASE.jar:4.3.21.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849) ~[spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760) ~[spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) ~[servlet-api-3.1.jar:3.1.0]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[servlet-api-3.1.jar:3.1.0]
```

**Comment by tesshucom** [comment]
Also, I can not play music on the web screen.
I have also changed the compilation to UTF-8, but with 100.1.0 the bug does not occur.

**Comment by tesshucom** [comment]
Normal migration was confirmed only when all data directories were deleted.

It is possible to release tomcat and jetty, with the condition that all data directories are deleted.

**Comment by tesshucom** [comment]
- Release jpsonic 100.1.0 as a stabilizer corresponding to 10.2.1-RELEASE.
 - The issue identified in this issue is the new issue corresponding to 10.3.0-SNAPSHOT.
