### ISSUE TITLE
Error suppression before index creation

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#191]
#187 is similar as a case.
Throwing an error in SearchService.
Change the message to output an easy-to-understand message because it is an error within the expected range of operation.
The log is long.

```

org.apache.lucene.index.IndexNotFoundException: no segments* file found in MMapDirectory@C:\jpsonic\lucene7.4jp\album lockFactory=org.apache.lucene.store.NativeFSLockFactory@68704d58: files: []
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:683) ~[lucene-core-7.4.0.jar!/:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:51:45]
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:80) ~[lucene-core-7.4.0.jar!/:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:51:45]
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63) ~[lucene-core-7.4.0.jar!/:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:51:45]
	at org.airsonic.player.service.SearchService.createIndexReader(SearchService.java:278) ~[classes!/:10.3.0-SNAPSHOT]
	at org.airsonic.player.service.SearchService.getRandomAlbums(SearchService.java:476) ~[classes!/:10.3.0-SNAPSHOT]
	at org.airsonic.player.controller.HomeController.getRandom(HomeController.java:195) [classes!/:10.3.0-SNAPSHOT]
	at org.airsonic.player.controller.HomeController.handleRequestInternal(HomeController.java:100) [classes!/:10.3.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_201]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [spring-web-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [javax.servlet-api-3.1.0.jar!/:3.1.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar!/:3.1.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.35.jar!/:8.5.35]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
	at org.airsonic.player.security.JWTRequestParameterProcessingFilter.doFilter(JWTRequestParameterProcessingFilter.java:61) [classes!/:10.3.0-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
	at org.airsonic.player.filter.MetricsFilter.doFilter(MetricsFilter.java:30) [classes!/:10.3.0-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
	at org.airsonic.player.filter.ResponseHeaderFilter.doFilter(ResponseHeaderFilter.java:49) [classes!/:10.3.0-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
	at org.airsonic.player.filter.RequestEncodingFilter.doFilter(RequestEncodingFilter.java:45) [classes!/:10.3.0-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
	at org.airsonic.player.filter.ParameterDecodingFilter.doFilter(ParameterDecodingFilter.java:57) [classes!/:10.3.0-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
	at org.airsonic.player.filter.BootstrapVerificationFilter.doFilter(BootstrapVerificationFilter.java:55) [classes!/:10.3.0-SNAPSHOT]
	at 
```

**Comment by tesshucom** [comment]
![image](https://user-images.githubusercontent.com/27724847/55042201-cf3f3d00-5073-11e9-8138-4a324eec08eb.png)


- Since an IndexReader can not be initialized is an expected normal operation immediately after installation, an appropriate message and warn are output with IOException.
- Improve internal code on the premise of steam. Acquisition of Reader should be Optional

**Comment by jp-searching** [comment]
Optional is not used because many IO processes are not the end of the process.

(1)Displayed Home before scanning at initial startup.

Screen is blank, error message.
Warming in the log.

![image](https://user-images.githubusercontent.com/47806044/55072448-7c46a380-50ce-11e9-89ec-0bda9fe71621.png)

![image](https://user-images.githubusercontent.com/27724847/55072304-15c18580-50ce-11e9-88e9-842c02cf1b06.png)


(2)Shuffle search before scanning at initial startup.
Nothing happens on the screen and no error is output.


(3)Name search before scanning at initial startup.

Screen is a normal "missing" message.
In the log warning.


![image](https://user-images.githubusercontent.com/47806044/55073204-72be3b00-50d0-11e9-93bc-8ad2814c9981.png)

![image](https://user-images.githubusercontent.com/47806044/55073292-aac57e00-50d0-11e9-869e-5bd136e0ecfe.png)

(4)
It was confirmed that scanning was performed after (1) to (3) operations were continuously performed, and the (1) to (3) operations operated normally.
