### ISSUE TITLE
JavaScript does not work

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#192]
Several complex problems occur at the junction with SNAPSHOT.
#170

## Problem description

An error occurred in DwrServlet.
Script like play button does not work.
DWR has not been initialized.

### Steps to reproduce
Capture 10.3.0-SNAPSHOT.

To be precise, it occurs when you upgrade DWR to 3.0.2-RELEASE.
It does not occur if it is 3.0.rc1.

## LOG

```
o.d.servlet.DwrServlet                   : init failed

org.directwebremoting.extend.ContainerConfigurationException: java.lang.IllegalArgumentException: name
        at org.directwebremoting.impl.StartupUtil.createAndSetupDefaultContainer(StartupUtil.java:194) ~[dwr-3.0.2-RELEASE.jar!/:na]
        at org.directwebremoting.servlet.DwrServlet.createContainer(DwrServlet.java:101) ~[dwr-3.0.2-RELEASE.jar!/:na]
        at org.directwebremoting.servlet.DwrServlet.init(DwrServlet.java:64) ~[dwr-3.0.2-RELEASE.jar!/:na]
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:789) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_201]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_201]
Caused by: java.lang.IllegalArgumentException: name
        at sun.misc.URLClassPath$Loader.getResource(Unknown Source) ~[na:1.8.0_201]
        at sun.misc.URLClassPath.getResource(Unknown Source) ~[na:1.8.0_201]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_201]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_201]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_201]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_201]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[jpsonic.war:10.3.0-SNAPSHOT]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_201]
        at java.lang.Class.forName0(Native Method) ~[na:1.8.0_201]
        at java.lang.Class.forName(Unknown Source) ~[na:1.8.0_201]
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadFromParent(TomcatEmbeddedWebappClassLoader.java:93) ~[spring-boot-1.5.18.RELEASE.jar!/:1.5.18.RELEASE]
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedWebappClassLoader.doLoadClass(TomcatEmbeddedWebappClassLoader.java:66) ~[spring-boot-1.5.18.RELEASE.jar!/:1.5.18.RELEASE]
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadClass(TomcatEmbeddedWebappClassLoader.java:50) ~[spring-boot-1.5.18.RELEASE.jar!/:1.5.18.RELEASE]
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1156) ~[tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.directwebremoting.util.LocalUtil.classForName(LocalUtil.java:1197) ~[dwr-3.0.2-RELEASE.jar!/:na]
        at org.directwebremoting.impl.DefaultContainer.addParameter(DefaultContainer.java:124) ~[dwr-3.0.2-RELEASE.jar!/:na]
        at org.directwebremoting.impl.StartupUtil.setupDefaults(StartupUtil.java:565) ~[dwr-3.0.2-RELEASE.jar!/:na]
        at org.directwebremoting.impl.StartupUtil.setupDefaultContainer(StartupUtil.java:246) ~[dwr-3.0.2-RELEASE.jar!/:na]
        at org.directwebremoting.impl.StartupUtil.createAndSetupDefaultContainer(StartupUtil.java:189) ~[dwr-3.0.2-RELEASE.jar!/:na]
        ... 20 common frames omitted

```
## Note

The YahooJSCompressor error mentioned in #170 is a side effect related to the DWR version upgrade in this case.
When DWR is 3.0.rc1, No error occurs when yuicompressor is 2.3.6 or 2.4.8.

```
WARN --- o.d.servlet.JavaScriptHandler            : Compression system (YahooJSCompressor) failed to compress script

java.lang.RuntimeException: null
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.printSourceNumber(JavaScriptCompressor.java:299) ~[yuicompressor-2.3.6.jar:na]
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:335) ~[yuicompressor-2.3.6.jar:na]
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:532) ~[yuicompressor-2.3.6.jar:na]
        at org.directwebremoting.impl.YahooJSCompressor.compressJavaScript(YahooJSCompressor.java:76) ~[dwr-3.0.2-RELEASE.jar:na]
        at org.directwebremoting.servlet.JavaScriptHandler.generateCachableContent(JavaScriptHandler.java:55) ~[dwr-3.0.2-RELEASE.jar:na]
        at org.directwebremoting.servlet.FileJavaScriptHandler.generateCachableContent(FileJavaScriptHandler.java:61) [dwr-3.0.2-RELEASE.jar:na]
        at org.directwebremoting.servlet.CachingHandler.handle(CachingHandler.java:74) [dwr-3.0.2-RELEASE.jar:na]
        at org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:211) [dwr-3.0.2-RELEASE.jar:na]
        at org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:185) [dwr-3.0.2-RELEASE.jar:na]
        at org.directwebremoting.servlet.DwrServlet.doPost(DwrServlet.java:144) [dwr-3.0.2-RELEASE.jar:na]
        at org.directwebremoting.servlet.DwrServlet.doGet(DwrServlet.java:131) [dwr-3.0.2-RELEASE.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [servlet-api-3.1.jar:3.1.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
```

**Comment by tesshucom** [comment]
- Only the DWR version is downgraded to DWR 3.0.rc1 adopted in 10.2.1-RELEASE. Others use what is adopted by 10.3.0-SNAPSHOT.
 - Write this on [wiki](https://github.com/jpsonic/jpsonic/wiki).

**Comment by tesshucom** [comment]
There is a similar update on the Airsonic, so reset and load the Airsonic update.
Merge to 101.0.0 if there is no problem in operation.

**Comment by tesshucom** [comment]
no problem!
