### ISSUE TITLE
 Eliminate errors when scanning

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#224]
Occasionally the same error occurs when scanning.
After examining it briefly, it seems  defective.
Investigate the cause and make corrections if possible.

```
java.lang.IllegalArgumentException: startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=0,lastStartOffset=6 for field 'artR'
        at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:824) ~[lucene-core-7.7.1.jar!/:7.7.1 5bf96d32f88eb8a2f5e775339885cd6ba84a3b58 - ishan - 2019-02-23 02:33:50]
        at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:430) ~[lucene-core-7.7.1.jar!/:7.7.1 5bf96d32f88eb8a2f5e775339885cd6ba84a3b58 - ishan - 2019-02-23 02:33:50]
        at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:394) ~[lucene-core-7.7.1.jar!/:7.7.1 5bf96d32f88eb8a2f5e775339885cd6ba84a3b58 - ishan - 2019-02-23 02:33:50]
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:251) ~[lucene-core-7.7.1.jar!/:7.7.1 5bf96d32f88eb8a2f5e775339885cd6ba84a3b58 - ishan - 2019-02-23 02:33:50]
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:494) ~[lucene-core-7.7.1.jar!/:7.7.1 5bf96d32f88eb8a2f5e775339885cd6ba84a3b58 - ishan - 2019-02-23 02:33:50]
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1616) ~[lucene-core-7.7.1.jar!/:7.7.1 5bf96d32f88eb8a2f5e775339885cd6ba84a3b58 - ishan - 2019-02-23 02:33:50]
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1608) ~[lucene-core-7.7.1.jar!/:7.7.1 5bf96d32f88eb8a2f5e775339885cd6ba84a3b58 - ishan - 2019-02-23 02:33:50]
        at org.airsonic.player.service.SearchService.index(SearchService.java:219) ~[classes!/:10.3.0-SNAPSHOT]
        at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:251) [classes!/:10.3.0-SNAPSHOT]
        at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:261) [classes!/:10.3.0-SNAPSHOT]
        at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:264) [classes!/:10.3.0-SNAPSHOT]
        at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:264) [classes!/:10.3.0-SNAPSHOT]
        at org.airsonic.player.service.MediaScannerService.doScanLibrary(MediaScannerService.java:193) [classes!/:10.3.0-SNAPSHOT]
        at org.airsonic.player.service.MediaScannerService.access$000(MediaScannerService.java:47) [classes!/:10.3.0-SNAPSHOT]
        at org.airsonic.player.service.MediaScannerService$2.run(MediaScannerService.java:161) [classes!/:10.3.0-SNAPSHOT]
```

___

There are a small number of unindexed records. Identify and resolve the cause.

**Comment by tesshucom** [comment]
Lucene 7, token offsets should follow new regulations that have not been demanded before.
The start offset of a token must be larger or equal than the end offset of its previous tokens.
This disallow using the token's offset attribute for representing a span within the text. 
woom ...

**Comment by tesshucom** [comment]
There are too many security bugs in lucene-analyser-icu, so think about how to solve it yourself.
