### ISSUE TITLE
Incorrect driver acquisition method on Tomcat

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#521]
On Tomcat, some launch patterns can cause problems.
~~( Or this log may be due to the irregular environment under test.)~~

 - ~~Find out if it comes from Airsonic or is unique to Jpsonic.~~ From Airsonic.
 - ~~Test for Tomcat, including the patterns that cause problems.~~ When run on container instead of standalone

```
java.lang.RuntimeException: Failed to upgrade HSQLDB database
        at org.airsonic.player.util.LegacyHsqlUtil.upgradeHsqldbDatabaseSafely(LegacyHsqlUtil.java:217) ~[classes/:11.0.0-SNAPSHOT]
        at org.airsonic.player.Application.lambda$doConfigure$0(Application.java:173) ~[classes/:11.0.0-SNAPSHOT]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
        at org.springframework.boot.context.event.EventPublishingRunListener.contextLoaded(EventPublishingRunListener.java:93) ~[spring-boot-2.2.7.RELEASE.jar:2.2.7.RELEASE]
        at org.springframework.boot.SpringApplicationRunListeners.contextLoaded(SpringApplicationRunListeners.java:65) ~[spring-boot-2.2.7.RELEASE.jar:2.2.7.RELEASE]
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:393) ~[spring-boot-2.2.7.RELEASE.jar:2.2.7.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.2.7.RELEASE.jar:2.2.7.RELEASE]
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:152) [spring-boot-2.2.7.RELEASE.jar:2.2.7.RELEASE]
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:132) [spring-boot-2.2.7.RELEASE.jar:2.2.7.RELEASE]
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:92) [spring-boot-2.2.7.RELEASE.jar:2.2.7.RELEASE]
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172) [spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5245) [catalina.jar:8.5.31]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.5.31]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754) [catalina.jar:8.5.31]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730) [catalina.jar:8.5.31]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734) [catalina.jar:8.5.31]
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985) [catalina.jar:8.5.31]
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857) [catalina.jar:8.5.31]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: java.sql.SQLException: No suitable driver found for jdbc:hsqldb:file:c:\jpsonic/db/jpsonic;sql.enforce_size=false;sql.regular_names=false
```

**Comment by tesshucom** [comment]
Probably because I'm trying to change to an external resource connection in the next release. Jpsonic will try to change the legacy connection handling so as not to confuse the user.

**Comment by tesshucom** [comment]
Migration confirmed on Tomcat running on Java 8 and Java 11.
